language: node_js
node_js:
  - "9.7.1"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - echo "Deploying team SKILLUP JALA XD"
  - ng build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: Diego.Mejia@fundacion-jala.org
    on_success: Diego.Mejia@fundacion-jala.org
